redactor-upload:
    pattern:  /redactor/upload
    defaults: { _controller: VinceTypeBundle:Redactor:upload }
    requirements:
        _format: json
        _method: POST

redactor-list-files:
    pattern:  /redactor/list-files/{path}
    defaults: { _controller: VinceTypeBundle:Redactor:listFiles }
    requirements:
        _format: json
        _method: GET
        path: "^.+"

token-search:
    pattern:  /token/search
    defaults: { _controller: VinceTypeBundle:Token:search }
    requirements:
        _format: json
        _method: POST

autocomplete-search:
    pattern:  /autocomplete/search
    defaults: { _controller: VinceTypeBundle:Autocomplete:search }
    requirements:
        _format: json
        _method: POST