redactor-upload:
    pattern:  /redactor/upload
    defaults: { _controller: VinceTypeBundle:Redactor:upload }
    requirements:
        _format: json
        _method: POST

redactor-list-files:
    pattern:  /redactor/list-files
    defaults: { _controller: VinceTypeBundle:Redactor:listFiles }
    requirements:
        _format: json
        _method: GET

geolocation-list:
    pattern:  /geolocation/{class}
    defaults: { _controller: VinceTypeBundle:Geolocation:list }
    requirements:
        _format: json
        _method: GET
